language: c++

os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libqt4-dev; fi

script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      PATH=/usr/local/opt/qt/bin/:${PATH};
      lrelease gpxsee.pro
      qmake gpxsee.pro
      make
    else
      qmake CONFIG+=release PREFIX=/usr
      make -j$(nproc)
      make INSTALL_ROOT=appdir -j$(nproc) install ; find appdir/
      wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
      chmod a+x linuxdeployqt-continuous-x86_64.AppImage
      ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage
      wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
      bash upload.sh GPXSee*.AppImage* 
    fi
